project:
  name: s3-malware-scanner
  regions:
  - eu-west-1
  lambda_zip_path:
    "./builds/lambdas"
  build_submodules: false
  package_lambda: false
tests:
  default:
    template: "./cloudformation-templates/initialize.yml"
    parameters: {
      "TotalVirusApiKeyParameter": "$[taskcat_genpass_64]",
      "S3MalwareUploadBucketNameParameter": "$[taskcat_genuuid]",
      "S3MalwareLambdaBucketNameParameter": "s3-malware-scanner-lambda-functions",
      "S3MalwareScanQueueDelaySecondsParameter": "300",
      "S3MalwareQuarantineQueueDelaySecondsParameter": "10"
    }