version: 0.2

phases:
  pre_build:
    commands:
      - rm -rf node_modules
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install nodejs
      - npm install --production
  install:
    runtime-versions:
      docker: 18
artifacts:
  files:
    - virus-file-scan-lambda.js
    - services/*
    - node_modules/**/*
